%define GL_SMOOTH                       0x1D01
%define GL_DEPTH_TEST                   0x0B71
%define GL_LEQUAL                       0x0203
%define GL_PERSPECTIVE_CORRECTION_HINT  0x0C50
%define GL_NICEST                       0x1102

%define GL_NO_ERROR                     0x0
%define GL_DEBUG_OUTPUT                 0x92e0

%define GL_COLOR_BUFFER_BIT             0x00004000
%define GL_DEPTH_BUFFER_BIT             0x00000100

; glGetString constants
%define GL_VENDOR                       0x1f00
%define GL_RENDERER                     0x1f01
%define GL_VERSION                      0x1f02
%define GL_SHADING_LANGUAGE_VERSION     0x8b8c

