; =============== [OxNAG] ===============
; This file contains compile flags for
; the codebase. Enable them by 
; uncommenting them. Defining such flags
; prompts the NASM preprocessor to enable
; specific functionalities.
;
; This file should contain all possible
; feature flag uncommented or not.
; =======================================


; Enable to log on a separate console
%define LOG_TO_CONSOLE
